language: node_js

node_js: '10'

env:
  - YARN_GPG=no

cache:
  yarn: true

script:
  - yarn test
  - yarn lint

  - echo "Package app..."
  # 64-bit builds for the time being
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn package --platform=linux --arch=x64; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_OS_NAME" == "osx" ]; then yarn package:mac --platform=darwin --arch=x64; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_OS_NAME" == "windows" ]; then yarn package --platform=win32 --arch=x64; fi

os:
  - linux
  - osx
  - windows

before_deploy:
  # Create tag when no tag was added to the commit.
  - if [ "$TRAVIS_TAG" == "" ];
    then
      echo "Adding tag..."
      git config --local user.name hummingly;
      git config --local user.email 31522351+hummingly@users.noreply.github.com;
      export TRAVIS_TAG="Build-$(date +'%Y%m%d')-$(git log --format=%h -1)";
      git tag $TRAVIS_TAG;
    fi
  - echo "Compress build artifacts..."
  - if [ "$TRAVIS_OS_NAME" == "windows" ];
    then
      7z a -ttar -so -an release | 7z a -si Allusion-${TRAVIS_OS_NAME}_x64-${TRAVIS_BUILD_NUMBER}.tar.gz;
    else
      tar -zcf Allusion-${TRAVIS_OS_NAME}_x64-${TRAVIS_BUILD_NUMBER}.tar.gz release;
    fi
  - echo "Release ${TRAVIS_TAG}..."

deploy:
  provider: releases
  edge: true
  api_key:
    secure: HUdSp6H1WDhXVyEpII1IXWeqCoFVyMnMpkxTT6t2EeHXb2+gvxU6vIWoLcp8NnpA7W7Hu4nsJv8olii92IXMNQ4ZDwCAV8ymij3mqO1nbwB/+gLarji7UELEQmap9X1aZEAHhkjXMENWAPwauthr07bQIZuUbtL/e6urXxf8L8flAEL3J3UA2sqhu9ik8e11JaPR/orv3WC8Q8s3IE0GfMXZZKwC0zzMbllXy5m7HMuqgsD0Lz7pDWa64wG6MWBUmzwUPTNFVKA7xkJYwo7o73Y/hXIanxqfcg0paerzItOvhCfXtahcfwVae4jwCfK3/QKOsy9PKDsA3CI4vXqZRcuYbVFMihfplnHUHAInkFfDfFxaRH3TU34tYfDK/fJM3t7NhCV5mloNiT5EKzDnhFN6mGQUS2CY4cB+uaW/d33WHjJJzzbYZecWSa0/sYVSnrkisczb/oEBEI4GtNmtVL4ZFNYHE2MxBYE6KeEx6H6+NwxZduXwphFJunZQFylrK9C0w9RMVeZvmsKP69aAZ7O+6ZCeFyP1vTgp2NE2xPI5fZsqx/iKf3Ebxh77BYu6twWbeIMRlxBN+x5a2NBNa82UD2mxS7dTsHHlkR4fqZnUkny1XLpAfApsSMmUmjBdvcmc1Qe9rqO5rblajMz+zLuLR0d6gUV3RLLu0wFz+lw=
  file_glob: true
  file: 'Allusion-${TRAVIS_OS_NAME}_x64-${TRAVIS_BUILD_NUMBER}.tar.gz'
  tag_name: $TRAVIS_TAG
  on:
    branch: master

branches:
  except:
    - /^(?i:build)-.*$/
