[package]
name = "masonry"
version = "0.1.0"
authors = ["Remi van der Laan <R.M.vanderlaan@student.tudelft.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.69"

[lib]
crate-type = ["cdylib", "rlib"]
